source:
  third_party_source:
    filepath_regex: [".*/docs/.*", ".*/glog_bench/.*", ".*/glog_example/.*", ".*/loguru_bench/.*", ".*/loguru_example/.*", ".*/test/.*", ".*/loguru.cpp", ".*/loguru.hpp"]
